import fs from 'node:fs/promises';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import sharp from 'sharp';
import * as esbuild from 'esbuild';

const root=process.cwd(),theme=path.join(root,'theme'),dist=path.join(root,'dist');
const layout=await fs.readFile(path.join(theme,'layout','theme.html'),'utf8');
const legacyAssets=(process.env.MODOSHOP_ASSET_ORIGIN||'https://55d7d1a6652f926b7952058d16423d301a086ff6--gleaming-brigadeiros-c260a9.netlify.app').replace(/\/$/,'')+'/assets';
const exec=promisify(execFile);
async function copyTree(from,to){await fs.mkdir(to,{recursive:true});for(const e of await fs.readdir(from,{withFileTypes:true})){if(e.name==='README.md')continue;const s=path.join(from,e.name),d=path.join(to,e.name);if(e.isDirectory())await copyTree(s,d);else await fs.copyFile(s,d)}}
const readTheme=rel=>fs.readFile(path.join(theme,rel),'utf8');
const esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
await fs.rm(dist,{recursive:true,force:true});await fs.mkdir(dist,{recursive:true});
await copyTree(path.join(theme,'assets'),path.join(dist,'assets'));
await fs.copyFile(path.join(theme,'data','catalog-fallback.json'),path.join(dist,'assets','catalog-data.json'));
const required=['logo.png','hero-tech.png','hero-family.png','products/bandolero-usb.jpg','products/camara-bombillo-360.jpg','products/camara-dual-6mp.jpg','products/licuadora-portatil.jpg','products/masajeador-mini.jpg','products/microfono-v8.jpg','products/plancha-vapor-raf.jpg','products/radios-bf888s.jpg','products/tensiometro-brazalete.jpg','products/timbre-camara-wifi.jpg'];
for(const rel of required){const target=path.join(dist,'assets',rel);try{await fs.access(target)}catch{await fs.mkdir(path.dirname(target),{recursive:true});await exec('curl',['-fsSL','--retry','3','--connect-timeout','15',legacyAssets+'/'+rel,'-o',target])}}
const raster=[];async function collect(dir){for(const e of await fs.readdir(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())await collect(p);else if(/\.(png|jpe?g)$/i.test(e.name))raster.push(p)}}await collect(path.join(dist,'assets'));
for(const file of raster){try{const meta=await sharp(file,{failOn:'none'}).metadata(),out=file.replace(/\.(png|jpe?g)$/i,'.webp');await sharp(file,{failOn:'none'}).rotate().resize({width:Math.min(Number(meta.width||1600),1600),withoutEnlargement:true}).webp({quality:82}).toFile(out+'.tmp');await fs.rename(out+'.tmp',out);await fs.rm(file,{force:true})}catch{}}
async function rewriteTree(dir){for(const e of await fs.readdir(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory()){await rewriteTree(p);continue}if(!/\.(html|css|js|json|mjs)$/i.test(e.name))continue;let s=await fs.readFile(p,'utf8');s=s.replace(/(["'(=])\/?assets\/([^"'()\s<>]+)\.(png|jpe?g)(?=["'()\s<>])/gi,(m,prefix,name)=>prefix+'/assets/'+name+'.webp');await fs.writeFile(p,s,'utf8')}}await rewriteTree(path.join(dist,'assets'));
for(const file of await fs.readdir(path.join(dist,'assets','css'))){if(!file.endsWith('.css'))continue;const p=path.join(dist,'assets/css',file),o=await esbuild.transform(await fs.readFile(p,'utf8'),{loader:'css',minify:true,legalComments:'none'});await fs.writeFile(p,o.code,'utf8')}
for(const file of await fs.readdir(path.join(dist,'assets','js'))){if(!file.endsWith('.js'))continue;const p=path.join(dist,'assets/js',file),o=await esbuild.transform(await fs.readFile(p,'utf8'),{loader:'js',minify:true,legalComments:'none',target:'es2020'});await fs.writeFile(p,o.code,'utf8')}
const templates=path.join(theme,'templates');
for(const file of (await fs.readdir(templates)).filter(x=>x.endsWith('.json'))){const m=JSON.parse(await fs.readFile(path.join(templates,file),'utf8'));const part=rel=>rel?readTheme(rel):Promise.resolve('');const header=await part(m.header&&'snippets/'+m.header),sections=await Promise.all((m.content||[]).map(x=>part('sections/'+x))),footer=await part(m.footer&&'snippets/'+m.footer),overlays=await part(m.overlays&&'snippets/'+m.overlays),scripts=(m.scripts||[]).map(x=>'<script src="/assets/js/'+esc(x)+'" defer></script>').join(''),font=m.font||'Poppins:wght@400;500;600;700;800',preload=(m.preload||[]).map(x=>'<link rel="preload" as="image" href="'+String(x).replace(/\.(png|jpe?g)$/i,'.webp')+'" fetchpriority="high">').join('');const head='<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="'+esc(m.themeColor||'#111318')+'"><meta name="description" content="'+esc(m.description||'')+'"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family='+font+'&display=swap" rel="stylesheet"><title>'+esc(m.title||'ModoShop Venezuela')+'</title>'+preload+'<link rel="stylesheet" href="/assets/css/'+esc(m.css)+'">';const html=layout.replace('{{HEAD}}',head).replace('{{HEADER}}',header).replace('{{CONTENT}}',sections.join('')).replace('{{FOOTER}}',footer).replace('{{OVERLAYS}}',overlays).replace('{{SCRIPTS}}',scripts);await fs.writeFile(path.join(dist,m.output),html,'utf8')}
await rewriteTree(dist);
const catalog=JSON.parse(await fs.readFile(path.join(theme,'data','catalog-fallback.json'),'utf8')),site=(process.env.URL||'https://gleaming-brigadeiros-c260a9.netlify.app').replace(/\/$/,''),urls=['/','/products','/cart','/checkout','/track','/admin.html','/success.html','/legal.html',...(catalog.products||[]).map(p=>'/products/'+encodeURIComponent(p.id))],today=new Date().toISOString().slice(0,10);
await fs.writeFile(path.join(dist,'robots.txt'),'User-agent: *\nAllow: /\nSitemap: '+site+'/sitemap.xml\n','utf8');
await fs.writeFile(path.join(dist,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+urls.map(u=>'<url><loc>'+site+u+'</loc><lastmod>'+today+'</lastmod></url>').join('')+'</urlset>','utf8');
console.log('ModoShop Shopify-inspired build complete');